# Generated by Django 4.1.4 on 2022-12-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("additionally", "0003_add_type_ticket"),
        ("ticket", "0002_alter_ticket_contractor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="type_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_ticket",
                to="additionally.dictionary",
                verbose_name="Тип заявки",
            ),
        ),
    ]
