# Generated by Django 4.1.4 on 2023-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0007_remove_comment_file_commentfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="metadata",
            field=models.CharField(
                blank=True,
                help_text="Дополнительная информация о заявке. Например номер магазина",
                max_length=255,
                null=True,
                verbose_name="Метадата",
            ),
        ),
    ]
