# Generated by Django 4.1.4 on 2023-01-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0009_ticket_planned_execution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="planned_execution_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Плановая дата выезда/исполнения"
            ),
        ),
    ]
