# Generated by Django 4.1.4 on 2023-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0010_alter_ticket_planned_execution_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ф.И.О заказчика"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телефон заказчика"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="position",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Должность заказчика"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="shop_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID магазина"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="metadata",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Другая информация"
            ),
        ),
    ]
