# Generated by Django 4.1.4 on 2023-01-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0011_ticket_full_name_ticket_phone_ticket_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="metadata",
            field=models.CharField(
                blank=True,
                help_text="Дополнительная информация о заявке. Которая не вошла в другие поля",
                max_length=100,
                null=True,
                verbose_name="Другая информация",
            ),
        ),
    ]
