# Generated by Django 4.1.4 on 2023-01-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0012_alter_ticket_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="id_email_message",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID письма в почте"
            ),
        ),
    ]
