# Generated by Django 4.1.4 on 2023-01-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0013_ticket_id_email_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="id_email_message",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID письма в почте"
            ),
        ),
    ]
