# Generated by Django 4.1.4 on 2023-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0015_alter_comment_author_alter_comment_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_changed",
            field=models.BooleanField(default=False),
        ),
    ]
