# Generated by Django 4.1.4 on 2023-01-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0017_commentimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-date_create",)},
        ),
    ]
