# Generated by Django 4.1.4 on 2023-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0018_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
    ]
