# Generated by Django 4.1.4 on 2023-02-10 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0019_comment_is_system_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-date_create"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заказчик",
            ),
            preserve_default=False,
        ),
    ]
