# Generated by Django 4.1.4 on 2023-02-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0020_alter_ticket_options_alter_ticket_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-date_create",),
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="commentfile",
            options={
                "verbose_name": "Файл комментария",
                "verbose_name_plural": "Файлы комментариев",
            },
        ),
        migrations.AlterModelOptions(
            name="commentimage",
            options={
                "verbose_name": "Изображение комментария",
                "verbose_name_plural": "Изображения комментариев",
            },
        ),
    ]
