# Generated by Django 4.1.4 on 2023-02-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0022_ticket_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="completion_date",
            field=models.DateField(
                blank=True,
                help_text="Дата завершения заявки",
                null=True,
                verbose_name="Дата завершения",
            ),
        ),
    ]
