# Generated by Django 4.1.4 on 2023-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0023_ticket_completion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="completion_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата завершения заявки",
                null=True,
                verbose_name="Дата завершения",
            ),
        ),
    ]
