# Generated by Django 4.1.4 on 2023-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0025_comment_is_for_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="date_to_work",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата взятия в работу",
                null=True,
                verbose_name="Дата взятия в работу",
            ),
        ),
    ]
