# Generated by Django 4.1.4 on 2023-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0026_ticket_date_to_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="_reply_to_emails",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Адреса для ответов",
            ),
        ),
    ]
