# Generated by Django 5.1 on 2024-10-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0027_ticket__reply_to_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="link_to_source",
            field=models.URLField(
                help_text="Если задача созджана через itsm, ссылка добавиться автоматически",
                null=True,
                verbose_name="Ссылка на источник",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="source_ticket",
            field=models.IntegerField(
                choices=[(1, "Email"), (2, "ITSM"), (3, "Ручное создание")],
                default=1,
                verbose_name="Источник задачи",
            ),
        ),
    ]
