# Generated by Django 5.1 on 2024-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0029_alter_ticket_link_to_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="id_itsm_comment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_for_itsm_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="status_itsm_push",
            field=models.BooleanField(default=False),
        ),
    ]
