# Generated by Django 5.1 on 2024-12-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0029_alter_ticket_link_to_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="shop_id",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="ID магазина"
            ),
        ),
    ]
