# Generated by Django 5.1 on 2024-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0030_comment_id_itsm_comment_comment_is_for_itsm_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="itsm_task_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ID задачи в itsm"
            ),
        ),
    ]
