# Generated by Django 5.1 on 2024-11-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0031_ticket_itsm_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="itsm_type_task",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Тип задачи в itsm itsm_request или itsm_incident",
            ),
        ),
    ]
