# Generated by Django 4.1.4 on 2023-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("OPERATOR", "Оператор"),
                    ("CUSTOMER", "Заказчик"),
                    ("CONTRACTOR", "Исполнитель"),
                    ("OTHER", "Не назначен"),
                ],
                max_length=50,
            ),
        ),
    ]
