# Generated by Django 4.1.4 on 2022-12-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DictionaryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код типа словаря"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=150, verbose_name="Описание типа словаря"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код словаря"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Описание словаря"),
                ),
                (
                    "type_dict",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="additionally.dictionarytype",
                        verbose_name="Тип словаря",
                    ),
                ),
            ],
        ),
    ]
