# Generated by Django 4.1.4 on 2022-12-27 10:58

from django.db import migrations


def add_status(apps, schema_editor):
    DictionaryType = apps.get_model("additionally", "DictionaryType")
    Dictionary = apps.get_model("additionally", "Dictionary")
    status_code = DictionaryType.objects.create(
        code="status_ticket", description="Словарь статусов"
    )
    status_codes = [
        ("work", "В работе"),
        ("search_contractor", "В поиске исполнителя"),
        ("consideration", "На рассмотрении"),
        ("revision", "Требуется доработка"),
        ("done", "Выполнено"),
    ]
    for code, description in status_codes:
        Dictionary.objects.create(
            type_dict=status_code, code=code, description=description
        )


class Migration(migrations.Migration):

    dependencies = [
        ("additionally", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_status),
    ]
