# Generated by Django 4.1.4 on 2022-12-28 08:05

from django.db import migrations


def add_ticket_type(apps, schema_editor):
    DictionaryType = apps.get_model("additionally", "DictionaryType")
    Dictionary = apps.get_model("additionally", "Dictionary")
    status_code = DictionaryType.objects.create(
        code="type_ticket", description="Словарь типов заявок"
    )
    status_codes = [
        ("repair", "Ремонт"),
        ("hardware_setup", "Настройка оборудования"),
    ]
    for code, description in status_codes:
        Dictionary.objects.create(
            type_dict=status_code, code=code, description=description
        )


class Migration(migrations.Migration):

    dependencies = [
        ("additionally", "0002_create_status_codes_dict"),
    ]

    operations = [
        migrations.RunPython(add_ticket_type),
    ]
