version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./.env

  beat:
    build: ./app
    command: celery -A ticsys beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq

  worker:
    build: ./app
    command: celery -A ticsys worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
