version: '3.8'

services:
  web:
    build: ./app
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 ticsys.asgi:application --access-log=logs/daphne.access.log
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 127.0.0.1:8001:8000
    env_file:
      - ./.env
    entrypoint:
      - RABBIT_HOST=rabbitmq
      - EMAIL_PORT="1025"
      - EMAIL_HOST="mailhog"
      - EMAIL_USE_SSL=off
      - REDIS_HOST="redis"

  beat:
    build: ./app
    restart: always
    command: celery -A ticsys beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    entrypoint:
      - RABBIT_HOST=rabbitmq
      - EMAIL_PORT="1025"
      - EMAIL_HOST="mailhog"
      - EMAIL_USE_SSL=off
      - REDIS_HOST="redis"
    depends_on:
      - rabbitmq

  worker:
    build: ./app
    restart: always
    command: celery -A ticsys worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    environment:
      - RABBIT_HOST=rabbitmq
      - EMAIL_PORT="1025"
      - EMAIL_HOST="mailhog"
      - EMAIL_USE_SSL=off
      - REDIS_HOST="redis"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: always

  redis:
    image: redis:latest
    restart: always

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
