# Generated by Django 4.1.4 on 2023-10-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manufactures", "0020_alter_nomenclature_amperage_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=255)),
                (
                    "is_stock",
                    models.BooleanField(default=False, verbose_name="В наличии"),
                ),
                (
                    "date_delivery",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "is_reserve",
                    models.BooleanField(default=False, verbose_name="Резерв"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("date_delivery", models.DateField(verbose_name="Дата получения")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "components",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deliveries",
                        to="storage.component",
                        verbose_name="Компоненты",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Если отмечено, то компонент  будет отображаться в списке компонентов только для инженеров",
                        verbose_name="Для внутреннего использования",
                    ),
                ),
                (
                    "sub_component_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите тип компонента, в состав которого входит данный компонент",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.componenttype",
                        verbose_name="Тип подкомпонента",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="component",
            name="component_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.componenttype",
                verbose_name="Тип компонента",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="nomenclature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufactures.nomenclature",
                verbose_name="Номенклатура",
            ),
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.componenttype",
                        verbose_name="Тип компонента",
                    ),
                ),
            ],
        ),
    ]
