# Generated by Django 4.1.4 on 2023-11-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componenttype",
            name="sub_component_type",
        ),
        migrations.AddField(
            model_name="componenttype",
            name="parent_component_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите тип компонента, в состав которого входит данный компонент",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_components_type",
                to="storage.componenttype",
                verbose_name="Тип подкомпонента",
            ),
        ),
    ]
