# Generated by Django 4.1.4 on 2023-12-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_remove_componenttype_sub_component_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alias",
            options={"verbose_name": "Алиас", "verbose_name_plural": "Алиасы"},
        ),
        migrations.AlterUniqueTogether(
            name="alias",
            unique_together={("name", "component_type")},
        ),
    ]
