# Generated by Django 4.1.4 on 2023-12-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_alter_alias_options_alter_alias_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Алиас"),
        ),
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название компонента"),
        ),
        migrations.AlterField(
            model_name="component",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Серийный номер"
            ),
        ),
        migrations.AlterField(
            model_name="componenttype",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название типа компонента"
            ),
        ),
        migrations.AlterField(
            model_name="componenttype",
            name="parent_component_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите тип компонента, в состав которого входит данный компонент",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_components_type",
                to="storage.componenttype",
                verbose_name="Тип родительского подкомпонента",
            ),
        ),
    ]
