# Generated by Django 4.1.4 on 2023-12-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_alter_alias_name_alter_component_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"verbose_name": "Компонент", "verbose_name_plural": "Компоненты"},
        ),
        migrations.RemoveField(
            model_name="component",
            name="name",
        ),
    ]
