# Generated by Django 4.1.4 on 2024-01-04 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_alter_componenttype_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="component",
            managers=[
                ("active_components", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SubComponentTypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count_sub_components",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "parent_component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_components",
                        to="storage.componenttype",
                        verbose_name="Родительский компонент",
                    ),
                ),
                (
                    "sub_component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_components",
                        to="storage.componenttype",
                        verbose_name="Тип подкомпонента",
                    ),
                ),
            ],
        ),
    ]
