# Generated by Django 4.1.4 on 2024-01-04 08:29

from django.db import migrations


def save_relationship_sub_component(apps, schema_editor):
    ComponentType = apps.get_model("storage", "ComponentType")
    SubComponentTypeRelation = apps.get_model("storage", "SubComponentTypeRelation")

    for component_type in ComponentType.objects.all():
        for sub_component_type in component_type.sub_components_type.all():
            SubComponentTypeRelation.objects.create(
                parent_component_type=component_type,
                sub_component_type=sub_component_type,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0011_alter_component_managers_subcomponenttyperelation"),
    ]

    operations = [
        migrations.RunPython(save_relationship_sub_component),
    ]
