# Generated by Django 4.1.4 on 2024-01-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0012_save_relationship_sub_component"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componenttype",
            name="parent_component_type",
        ),
    ]
