# Generated by Django 4.1.4 on 2024-01-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_remove_componenttype_parent_component_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="componenttype",
            name="parent_component_type",
            field=models.ManyToManyField(
                help_text="Выберите тип компонента, в состав которого входит данный компонент",
                related_name="sub_components_type",
                through="storage.SubComponentTypeRelation",
                to="storage.componenttype",
                verbose_name="Тип родительского подкомпонента",
            ),
        ),
    ]
