# Generated by Django 4.1.4 on 2024-01-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0015_alter_subcomponenttyperelation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-date_delivery"],
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
            },
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="components",
        ),
        migrations.AddField(
            model_name="component",
            name="delivery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.delivery",
                verbose_name="Доставка",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="status",
            field=models.IntegerField(
                choices=[(10, "Создана"), (30, "Завершена"), (50, "Отменена")],
                default=10,
                verbose_name="Статус",
            ),
        ),
    ]
