# Generated by Django 4.1.4 on 2024-06-05 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0027_ticket__reply_to_emails"),
        ("storage", "0018_alter_componenttype_is_internal"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ticket.ticket",
                verbose_name="Задача",
            ),
        ),
    ]
