# Generated by Django 5.1 on 2024-09-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0018_alter_componenttype_is_internal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                (
                    "file_invoice",
                    models.FileField(
                        upload_to="secret/invoice/%Y/%m/", verbose_name="Счет"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(10, "В работе"), (20, "Обработан"), (100, "Ошибка")],
                        default=10,
                        verbose_name="Статус",
                    ),
                ),
                ("alias", models.ManyToManyField(to="storage.alias")),
                (
                    "delivery",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.delivery",
                        verbose_name="Доставка",
                    ),
                ),
            ],
        ),
    ]
