# Generated by Django 5.1 on 2024-09-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0019_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.IntegerField(
                choices=[
                    (5, "Черновик"),
                    (10, "Создана"),
                    (30, "Завершена"),
                    (50, "Отменена"),
                ],
                default=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="delivery",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.delivery",
                verbose_name="Доставка",
            ),
        ),
    ]
