# Generated by Django 5.1 on 2024-09-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0021_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "verbose_name": "Счет на доставку",
                "verbose_name_plural": "Счета на доставку",
            },
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="alias",
        ),
        migrations.AlterField(
            model_name="alias",
            name="component_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.componenttype",
                verbose_name="Тип компонента",
            ),
        ),
        migrations.AlterField(
            model_name="alias",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Алиас"),
        ),
    ]
