# Generated by Django 5.1 on 2024-09-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0022_alter_invoice_options_remove_invoice_alias_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceAliasRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "alias",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alias",
                        to="storage.alias",
                        verbose_name="Алиас компонента",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="storage.invoice",
                        verbose_name="Счет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь счетов и компонентов через алиас",
                "verbose_name_plural": "Связи счетов и компонентов через алиас",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="alias",
            field=models.ManyToManyField(
                through="storage.InvoiceAliasRelation", to="storage.alias"
            ),
        ),
    ]
