# Generated by Django 5.1 on 2024-12-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0041_alter_manufacture_ticket"),
        ("storage", "0024_alter_alias_name_alter_invoice_delivery"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="component",
            managers=[],
        ),
        migrations.AlterField(
            model_name="component",
            name="nomenclature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="components",
                to="manufactures.nomenclature",
                verbose_name="Номенклатура",
            ),
        ),
    ]
