# Generated by Django 5.1 on 2025-01-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0025_alter_component_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="serial_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Серийный номер",
            ),
        ),
    ]
