# Generated by Django 4.1.4 on 2023-01-12 19:12

from django.db import migrations


def add_robot_user_for_save_email(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.create(username="email_robot", email="email_robor@ticket.ru")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(add_robot_user_for_save_email),
    ]
