# Generated by Django 4.1.4 on 2023-01-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_robot_user_for_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="parser",
            field=models.CharField(
                default="base", max_length=50, verbose_name="Парсер"
            ),
        ),
    ]
