# Generated by Django 4.1.4 on 2023-01-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_contractorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorprofile",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание"),
        ),
    ]
