# Generated by Django 4.1.4 on 2023-02-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_contractorprofile_company_user_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notify",
            field=models.BooleanField(default=True, verbose_name="Уведомлять по email"),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_notify",
            field=models.BooleanField(
                default=False, verbose_name="Уведомлять в Telegram"
            ),
        ),
    ]
