# Generated by Django 4.1.4 on 2023-02-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_email_notify_user_telegram_notify"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="company",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Компания"
            ),
        ),
    ]
