# Generated by Django 4.1.4 on 2023-02-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customerprofile_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=72, null=True, verbose_name="Телефон"
            ),
        ),
    ]
