# Generated by Django 4.1.4 on 2023-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_contractor_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="_emails",
            field=models.CharField(
                blank=True,
                db_column="emails",
                max_length=500,
                null=True,
                verbose_name="Адреса, которые должны быть в копии",
            ),
        ),
    ]
