# Generated by Django 4.1.4 on 2023-05-10 18:14

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    UserModel = apps.get_model("users", "User")
    for row in UserModel.objects.all():
        row.token = uuid.uuid4()
        row.save(update_fields=["token"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_token"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
