# Generated by Django 4.1.4 on 2023-05-10 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_populate_user_tocken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
