# Generated by Django 4.1.4 on 2023-05-28 15:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_token_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[],
            options={
                "verbose_name": "Производство",
                "verbose_name_plural": "Производства",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.ManufacturerManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("OPERATOR", "Оператор"),
                    ("CUSTOMER", "Заказчик"),
                    ("CONTRACTOR", "Исполнитель"),
                    ("MANUFACTURER", "Производство"),
                    ("OTHER", "Не назначен"),
                ],
                max_length=50,
                verbose_name="Роль",
            ),
        ),
    ]
