# Generated by Django 4.1.4 on 2024-01-14 16:10

from django.db import migrations
from users.models import User as U_models


def create_groups_from_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("users", "User")
    Roles = U_models.Role
    for role in Roles:
        Group.objects.get_or_create(name=role)

    for user in User.objects.all():
        if user.role:
            group = Group.objects.get(name=user.role)
            user.groups.add(group)
            continue
        user.groups.add(Group.objects.get(name=Roles.OTHER))


def remove_groups_from_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("users", "User")
    Roles = U_models.Role

    for role in Roles:
        Group.objects.get(name=role).delete()

    for user in User.objects.all():
        user.groups.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_manufacturer_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(create_groups_from_roles, remove_groups_from_roles),
    ]
