# Generated by Django 4.1.4 on 2023-05-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0017_manufacturer_alter_user_role"),
        ("additionally", "0007_add_status_cancel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатуры",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Manufacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField(default=1, verbose_name="Количество")),
                (
                    "date_shipment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата отгрузки"
                    ),
                ),
                (
                    "branding",
                    models.BooleanField(default=False, verbose_name="Брендирование"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufactures",
                        to="manufactures.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "nomenclatures",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manufactures",
                        to="manufactures.nomenclature",
                        verbose_name="Номенклатуры",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.operator",
                        verbose_name="Оператор",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        help_text="В ожидании, в работе ...",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufactures_status",
                        to="additionally.dictionary",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на производство",
                "verbose_name_plural": "Заявки на производство",
                "ordering": ["-date_create"],
            },
        ),
    ]
