# Generated by Django 4.1.4 on 2023-06-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclature",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
    ]
