# Generated by Django 4.1.4 on 2023-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0003_remove_manufacture_nomenclatures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacture",
            name="nomenclatures",
            field=models.ManyToManyField(
                blank=True,
                related_name="manufactures",
                through="manufactures.ManufactureNomenclature",
                to="manufactures.nomenclature",
                verbose_name="Номенклатуры",
            ),
        ),
    ]
