# Generated by Django 4.1.4 on 2023-06-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0005_remove_nomenclature_comment_nomenclature_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturenomenclature",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
