# Generated by Django 4.1.4 on 2023-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0006_alter_manufacturenomenclature_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacture",
            name="count",
        ),
        migrations.AlterField(
            model_name="manufacturenomenclature",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
