# Generated by Django 4.1.4 on 2023-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0008_nomenclature_bd_count_nomenclature_bd_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nomenclature",
            options={
                "ordering": ["-date_create"],
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатуры",
            },
        ),
        migrations.RemoveField(
            model_name="nomenclature",
            name="description",
        ),
        migrations.RemoveField(
            model_name="nomenclature",
            name="name",
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
