# Generated by Django 4.1.4 on 2023-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0009_alter_nomenclature_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacture",
            name="nomenclatures",
        ),
        migrations.AddField(
            model_name="manufacture",
            name="count",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.DeleteModel(
            name="ManufactureNomenclature",
        ),
    ]
