# Generated by Django 4.1.4 on 2023-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufactures",
            "0010_remove_manufacture_nomenclatures_manufacture_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacture",
            name="nomenclatures",
            field=models.ManyToManyField(
                blank=True,
                related_name="manufactures",
                to="manufactures.nomenclature",
                verbose_name="Номенклатуры",
            ),
        ),
    ]
