# Generated by Django 4.1.4 on 2023-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0011_manufacture_nomenclatures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomenclature",
            name="bd_count",
        ),
        migrations.RemoveField(
            model_name="nomenclature",
            name="bd_type",
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="bp_count",
            field=models.IntegerField(default=1, verbose_name="Количество БП"),
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="bp_type",
            field=models.CharField(
                choices=[("IN", "Внутренний"), ("OU", "Внешний")],
                default="IN",
                max_length=2,
                verbose_name="Тип БП",
            ),
        ),
    ]
