# Generated by Django 4.1.4 on 2023-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufactures",
            "0013_alter_nomenclature_options_nomenclature_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclature",
            name="status_int",
            field=models.IntegerField(
                choices=[(1, "Новый"), (2, "В работе"), (3, "Готово")],
                default=1,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="body",
            field=models.CharField(
                choices=[
                    ("PL", "Плекс"),
                    ("PR", "Профиль"),
                    ("SW", "S Белый"),
                    ("SG", "S Серый"),
                    ("SB", "S Черный"),
                ],
                default="PL",
                max_length=2,
                verbose_name="Корпус",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="status",
            field=models.TextField(
                choices=[("NW", "Новый"), ("IP", "В работе"), ("RD", "Готово")],
                default="NW",
                verbose_name="Статус",
            ),
        ),
    ]
