# Generated by Django 4.1.4 on 2023-07-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manufactures",
            "0014_nomenclature_status_int_alter_nomenclature_body_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomenclature",
            name="status",
        ),
        migrations.RenameField(
            model_name="nomenclature",
            old_name="status_int",
            new_name="status",
        ),
    ]
