# Generated by Django 4.1.4 on 2023-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0015_remove_nomenclature_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclature",
            name="amperage_3_2",
            field=models.BooleanField(default=False, verbose_name="3.2 А"),
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="amperage_6",
            field=models.BooleanField(default=False, verbose_name="6 А"),
        ),
    ]
