# Generated by Django 4.1.4 on 2023-10-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0019_nomenclature_amperage_1_nomenclature_amperage_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclature",
            name="amperage_1",
            field=models.BooleanField(
                default=False, help_text="Amperage for AM", verbose_name="1 А"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="amperage_2",
            field=models.BooleanField(
                default=False, help_text="Amperage for AM", verbose_name="2 А"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="amperage_3_2",
            field=models.BooleanField(
                default=False, help_text="Amperage for RF", verbose_name="3.2 А"
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="amperage_6",
            field=models.BooleanField(
                default=False, help_text="Amperage for RF", verbose_name="6 А"
            ),
        ),
    ]
