# Generated by Django 4.1.4 on 2023-11-03 15:37

from django.db import migrations
import logging


def save_frame_type(apps, schema_editor):
    FrameType = apps.get_model("manufactures", "FrameTypeOption")
    AM = FrameType.objects.create(name="АМ")
    RF = FrameType.objects.create(name="РЧ")
    logging.info(f"FrameTypeOption: AM, RF created")
    Nomenclature = apps.get_model("manufactures", "Nomenclature")
    for nomenclature in Nomenclature.objects.all():
        if nomenclature.frame_type == "AM":
            nomenclature.frame_type_option = AM
        elif nomenclature.frame_type == "RF":
            nomenclature.frame_type_option = RF
        else:
            raise TypeError(f"{nomenclature.frame_type} is not processed")
        logging.info(f"save nomenclature {nomenclature.frame_type}")
        nomenclature.save()


class Migration(migrations.Migration):
    dependencies = [
        ("manufactures", "0022_frametypeoption_nomenclature_frame_type_option"),
    ]

    operations = [
        migrations.RunPython(save_frame_type),
    ]
