# Generated by Django 4.1.4 on 2023-11-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manufactures", "0023_save_all_frame_to_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomenclature",
            name="frame_type",
        ),
        migrations.RenameField(
            model_name="nomenclature",
            old_name="frame_type_option",
            new_name="frame_type",
        ),
    ]
