# Generated by Django 4.1.4 on 2023-11-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0024_remove_nomenclature_frame_type_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclature",
            name="_manufactures",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_nomenclatures",
                to="manufactures.manufacture",
                verbose_name="Заявка на производство",
            ),
        ),
    ]
