# Generated by Django 4.1.4 on 2023-11-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0026_save_nomenclature_manufacture_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacture",
            name="nomenclatures",
        ),
    ]
