# Generated by Django 4.1.4 on 2023-11-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0028_rename__manufactures_nomenclature_manufacture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclature",
            name="manufacture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nomenclatures",
                to="manufactures.manufacture",
                verbose_name="Заявка на производство",
            ),
        ),
    ]
