# Generated by Django 4.1.4 on 2023-11-07 20:23

from django.db import migrations, models
import django.db.models.deletion
import manufactures.models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0029_alter_nomenclature_manufacture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclature",
            name="frame_type",
            field=models.ForeignKey(
                default=manufactures.models.FrameTypeOption.get_default,
                on_delete=django.db.models.deletion.PROTECT,
                to="manufactures.frametypeoption",
                verbose_name="Тип",
            ),
        ),
    ]
