# Generated by Django 4.1.4 on 2023-12-26 17:41

from django.db import migrations, models
import django.db.models.deletion
import manufactures.models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0031_bodyoption_rename_body_nomenclature_body_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclature",
            name="body",
            field=models.ForeignKey(
                default=manufactures.models.BodyOption.get_default,
                on_delete=django.db.models.deletion.PROTECT,
                to="manufactures.bodyoption",
                verbose_name="Корпус",
            ),
        ),
    ]
