# Generated by Django 4.1.4 on 2023-12-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0033_save_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomenclature",
            name="body_option",
        ),
    ]
