# Generated by Django 4.1.4 on 2023-12-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0034_remove_nomenclature_body_option"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodyoption",
            options={
                "verbose_name": "Тип корпуса",
                "verbose_name_plural": "Типы корпусов",
            },
        ),
        migrations.AlterModelOptions(
            name="frametypeoption",
            options={"verbose_name": "Тип платы", "verbose_name_plural": "Типы плат"},
        ),
    ]
