# Generated by Django 4.1.4 on 2023-12-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0035_alter_bodyoption_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclature",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Новый"),
                    (2, "В работе"),
                    (3, "Готово"),
                    (4, "Отгружено"),
                    (5, "Отменено"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
