# Generated by Django 4.1.4 on 2024-01-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0036_alter_nomenclature_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nomenclature",
            options={
                "ordering": ["-date_create"],
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатуры",
            },
        ),
    ]
