# Generated by Django 4.1.4 on 2024-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0037_alter_nomenclature_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=50)),
                ("result", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
