# Generated by Django 4.1.4 on 2024-07-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0027_ticket__reply_to_emails"),
        ("manufactures", "0038_taskreservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacture",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="ticket.ticket",
                verbose_name="Заявка",
            ),
        ),
    ]
