# Generated by Django 4.1.4 on 2024-07-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0027_ticket__reply_to_emails"),
        ("manufactures", "0040_alter_manufacture_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacture",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufactures",
                to="ticket.ticket",
                verbose_name="Заявка",
            ),
        ),
    ]
