# Generated by Django 5.1 on 2025-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactures", "0041_alter_manufacture_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomenclature",
            name="is_reserving",
            field=models.BooleanField(default=False),
        ),
    ]
