# Generated by Django 4.1.4 on 2023-03-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_email_notification_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type_notify",
            field=models.CharField(
                choices=[
                    ("new_ticket", "Новая заявка"),
                    ("new_comment", "Новый комментарий"),
                    ("set_contractor", "Установлен подрядчик"),
                    ("ticket_to_work", "Заявка в работе"),
                    ("ticket_done", "Заявка выполнена"),
                    ("ticket_cancel", "Заявка отменена"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=50,
                verbose_name="Тип оповещения",
            ),
        ),
    ]
