# Generated by Django 4.1.4 on 2023-03-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0027_ticket__reply_to_emails"),
        ("notifications", "0005_notification_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="ticket.ticket",
            ),
        ),
    ]
