# Generated by Django 4.1.4 on 2023-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_notification_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="bcc_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
