# Generated by Django 4.1.4 on 2023-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_alter_notification_bcc_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="_cc_emails",
            field=models.CharField(
                blank=True,
                db_column="cc_emails",
                max_length=500,
                null=True,
                verbose_name="Копии",
            ),
        ),
    ]
