# Generated by Django 4.1.4 on 2023-02-15 17:38

from django.db import migrations


def add_status(apps, schema_editor):
    DictionaryType = apps.get_model("additionally", "DictionaryType")
    Dictionary = apps.get_model("additionally", "Dictionary")
    status_code = DictionaryType.objects.get(code="status_ticket")

    Dictionary.objects.create(
        type_dict=status_code, code="testing", description="Тестирование"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("additionally", "0004_add_type_ticket_new"),
    ]

    operations = [
        migrations.RunPython(add_status),
    ]
