# Generated by Django 4.1.4 on 2023-03-02 12:41

from django.db import migrations


def add_ticket_type(apps, schema_editor):
    DictionaryType = apps.get_model("additionally", "DictionaryType")
    Dictionary = apps.get_model("additionally", "Dictionary")
    type_dict = DictionaryType.objects.get(code="type_ticket")

    Dictionary.objects.create(
        type_dict=type_dict, code="warranty", description="Гарантийный ремонт"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("additionally", "0005_add_type_ticket_in_observation"),
    ]

    operations = [
        migrations.RunPython(add_ticket_type),
    ]
