# Generated by Django 4.1.4 on 2023-07-04 13:42

from django.db import migrations


def add_status(apps, schema_editor):
    DictionaryType = apps.get_model("additionally", "DictionaryType")
    Dictionary = apps.get_model("additionally", "Dictionary")
    status_code = DictionaryType.objects.get(code="status_manufactory")

    Dictionary.objects.create(
        type_dict=status_code, code="shipped", description="Отгружено"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("additionally", "0008_add_statuses_to_manuf"),
    ]

    operations = [
        migrations.RunPython(add_status),
    ]
