# Generated by Django 4.1.4 on 2023-02-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0026_ticket_date_to_work"),
        ("reports", "0002_act"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="ticket.ticket",
                verbose_name="Заявка",
            ),
        ),
    ]
