# Generated by Django 4.1.4 on 2023-02-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_act_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="act",
            name="file_act_pdf",
        ),
    ]
