# Generated by Django 4.1.4 on 2023-03-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_remove_act_file_act_pdf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="act",
            options={
                "verbose_name": "Акт выполненных работ",
                "verbose_name_plural": "Акты выполненных работ",
            },
        ),
    ]
