# Generated by Django 4.1.4 on 2022-12-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("additionally", "0003_add_type_ticket"),
        ("ticket", "0003_alter_ticket_type_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="В ожидании, в работе ...",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status",
                to="additionally.dictionary",
                verbose_name="Статус",
            ),
        ),
    ]
